project:
  type: website
  output-dir: docs
  render:
  - "*.ipynb"
  - "!exercises/"

website: 
  title: "Computational Tools for Physics"
  sidebar:
    style: "docked"
    search: true
    contents:
    - section: "NumPy"
      contents:
        - "numpy/arrays.ipynb"
        - "numpy/interpolation.ipynb"
        - "numpy/random.ipynb"
        - "numpy/vectors_matrices.ipynb"
        - "numpy/vectorfields.ipynb"
        - "numpy/broadcasting.ipynb"
    - section: "SciPy"
      contents:
        - "scipy/constants.ipynb"
        - "scipy/functions.ipynb"
        - "scipy/curvefit.ipynb"
        - "scipy/integration.ipynb"
    - section: "SymPy"
      contents:
        - "sympy/expressions.ipynb"
        - "sympy/equations.ipynb"
        - "sympy/calculus.ipynb"
    - section: "Matplotlib"
      contents:
        - "matplotlib/matplotlib.ipynb"
    - section: "Pint"
      contents:
        - "pint/pint.ipynb"
    - section: "Polars"
      contents:
        - "polars/intro_polars.ipynb"

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 4
    code-fold: false
    css: styles.css
